/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package larrys;


import java.awt.Desktop;
import java.awt.List;
import java.awt.datatransfer.StringSelection;
import java.awt.Toolkit;
import java.awt.datatransfer.Clipboard;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.net.URL;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author thedoc
 */
public class mainapp extends javax.swing.JFrame {
   mainapp ss;
  TimePlayed t;
  String SelectedEmployee;
  
    /**
     * Creates new form mainapp
     */
    public mainapp() {
        initComponents();
        this.setTitle("LarrysSales - El Origen Company");
        this.setResizable(false);
        ss = this;
        t = new TimePlayed(ss);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TimePlayedLabel = new javax.swing.JLabel();
        startstopbt = new javax.swing.JButton();
        pausebtt = new javax.swing.JButton();
        employeelist = new javax.swing.JComboBox<>();
        employechoosetitle = new javax.swing.JLabel();
        opencalc = new javax.swing.JButton();
        Play = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TimePlayedLabel.setText("Tiempo Jugado:");

        startstopbt.setText("Start");
        startstopbt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                startstopbtMouseClicked(evt);
            }
        });

        pausebtt.setText("Parar");
        pausebtt.setEnabled(false);
        pausebtt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pausebttMouseClicked(evt);
            }
        });
        pausebtt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pausebttKeyPressed(evt);
            }
        });

        employeelist.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un nombre", "Williams de los santos", "Marc Ortega", "Tuko Blessed" }));

        employechoosetitle.setText("Empleado: ");

        opencalc.setText("Calculadora de precios");
        opencalc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                opencalcMouseClicked(evt);
            }
        });

        Play.setText("Jugar");
        Play.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PlayMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(startstopbt, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pausebtt, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(TimePlayedLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(employeelist, 0, 175, Short.MAX_VALUE)
                            .addComponent(employechoosetitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(571, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(opencalc, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Play, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TimePlayedLabel)
                    .addComponent(employechoosetitle))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(startstopbt)
                    .addComponent(pausebtt)
                    .addComponent(employeelist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(opencalc))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(Play, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(311, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startstopbtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_startstopbtMouseClicked
        if(!t.isStarted()){
            int sel = employeelist.getSelectedIndex();
            if(sel != 0){
                SelectedEmployee = employeelist.getSelectedItem().toString();
                
                t.StartTimer();
                startstopbt.setEnabled(false);
                pausebtt.setEnabled(true);
                CopyToClipboard("Nombre: " + SelectedEmployee + "\n" + t.GetStartTime().toString());
                JOptionPane.showMessageDialog(null, "Horario de entrada copiado");
            }else{
                JOptionPane.showMessageDialog(null, "Porfavor seleccione un nombre antes de encender el temporizador");
            }
            
            
           
        }
        
    }//GEN-LAST:event_startstopbtMouseClicked

    
    
    
    
    private void pausebttMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pausebttMouseClicked
        if(t.started){
            t.StopTimer();
            String myString = t.getTiempo();
            CopyToClipboard("Nombre: " + SelectedEmployee + "\n" + myString); 
            t.ResetTimer();
            startstopbt.setEnabled(true);
            pausebtt.setEnabled(false);
            JOptionPane.showMessageDialog(null, "Horario Copiado");
        }
    }//GEN-LAST:event_pausebttMouseClicked

    private void pausebttKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pausebttKeyPressed
       
    }//GEN-LAST:event_pausebttKeyPressed

    private void opencalcMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_opencalcMouseClicked
        // Funcion para abrir calculadora
        PriceCalculator pp = new PriceCalculator();
        pp.setVisible(true);
        pp.requestFocus();
    }//GEN-LAST:event_opencalcMouseClicked

    private void PlayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PlayMouseClicked
       try {
           openweb("cfx.re/join/pqgb5y");
       } catch (IOException ex) {
           JOptionPane.showMessageDialog(null, ex);
       }
    }//GEN-LAST:event_PlayMouseClicked
    
    
    public void CopyToClipboard(String mystring){
        StringSelection stringSelection = new StringSelection(mystring);
        Clipboard clipboard = Toolkit.getDefaultToolkit().getSystemClipboard();
        clipboard.setContents(stringSelection, null);
    }
   
    
    public void openweb(String url) throws IOException{
       try {
           URI uri= new URI(url);
   
            java.awt.Desktop.getDesktop().browse(uri);
           
       } catch (URISyntaxException ex) {
           JOptionPane.showMessageDialog(null, ex);
       } catch (IOException e){
           JOptionPane.showMessageDialog(null, e);
       }
    }



    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws FileNotFoundException, IOException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainapp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainapp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainapp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainapp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainapp().setVisible(true);
                
            }
        });
         
         

        
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Play;
    public javax.swing.JLabel TimePlayedLabel;
    private javax.swing.JLabel employechoosetitle;
    private javax.swing.JComboBox<String> employeelist;
    private javax.swing.JButton opencalc;
    private javax.swing.JButton pausebtt;
    private javax.swing.JButton startstopbt;
    // End of variables declaration//GEN-END:variables
}
