/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package larrys;

import java.util.ArrayList;
import javax.swing.JComboBox;

/**
 *
 * @author thedoc
 */
public class PriceCalculator extends javax.swing.JFrame {
    ArrayList<String> carro;
    ArrayList<String> precc;
   
    /**
     * Creates new form PriceCalculator
     */
    public PriceCalculator() {
        initComponents();
        
        this.setTitle("Calculadora de precios - LarrysSales - El Origen Company");
        getvehicles coches = new getvehicles();
         Thread car = new Thread(coches);
         getprices precios = new getprices();
         Thread precio = new Thread(precios);
         
         car.run();
         precio.run();
          carro = coches.getvehicles();
          precc = precios.getprecio();
          
          
          for (int i = 0; i < carro.size(); i++) {
              cmitem ss = new cmitem(carro.get(i), precc.get(i));
            VehList.addItem(ss);
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PriceCalculatorTitle = new javax.swing.JLabel();
        TaxPriceLabel = new javax.swing.JLabel();
        VehPriceLabel = new javax.swing.JLabel();
        BuyPriceLabel = new javax.swing.JLabel();
        TunePriceLabel2 = new javax.swing.JLabel();
        SalePriceLabel = new javax.swing.JLabel();
        TaxPriceInput = new javax.swing.JTextField();
        VehPriceInput1 = new javax.swing.JTextField();
        TunePriceInput1 = new javax.swing.JTextField();
        BuyPriceInput = new javax.swing.JTextField();
        SalePriceInput = new javax.swing.JTextField();
        VehList = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        PriceCalculatorTitle.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        PriceCalculatorTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PriceCalculatorTitle.setText("Calculadora de precios");

        TaxPriceLabel.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        TaxPriceLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TaxPriceLabel.setText("Precio de Tasación");

        VehPriceLabel.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        VehPriceLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        VehPriceLabel.setText("Coste del Vehiculo");

        BuyPriceLabel.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        BuyPriceLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BuyPriceLabel.setText("Precio de Compra");

        TunePriceLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        TunePriceLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TunePriceLabel2.setText("Coste del Tunning");

        SalePriceLabel.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        SalePriceLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SalePriceLabel.setText("Valor de Venta");

        TaxPriceInput.setEditable(false);

        VehPriceInput1.setEditable(false);
        VehPriceInput1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                VehPriceInput1KeyPressed(evt);
            }
        });

        TunePriceInput1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TunePriceInput1KeyReleased(evt);
            }
        });

        BuyPriceInput.setEditable(false);

        SalePriceInput.setEditable(false);

        VehList.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                VehListItemStateChanged(evt);
            }
        });
        VehList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VehListMouseClicked(evt);
            }
        });
        VehList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VehListActionPerformed(evt);
            }
        });

        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel1.setText("Introduzca vehiculo debajo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(PriceCalculatorTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(SalePriceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(SalePriceInput, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(TunePriceLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TunePriceInput1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BuyPriceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BuyPriceInput, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(TaxPriceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TaxPriceInput, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(VehPriceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextField1)
                                        .addComponent(VehList, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(VehPriceInput1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 178, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PriceCalculatorTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(VehList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VehPriceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VehPriceInput1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TunePriceLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TunePriceInput1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TaxPriceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TaxPriceInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BuyPriceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BuyPriceInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SalePriceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SalePriceInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 88, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VehPriceInput1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_VehPriceInput1KeyPressed
        
    }//GEN-LAST:event_VehPriceInput1KeyPressed

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
       
        
    }//GEN-LAST:event_jTextField1KeyPressed

    private void VehListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VehListMouseClicked
        
        
    }//GEN-LAST:event_VehListMouseClicked

    private void VehListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VehListActionPerformed
       
            Object item = VehList.getSelectedItem();
            if(item != null){
                String value = ((cmitem)item).getValue();
                VehPriceInput1.setText(value);
            }
            
        
    }//GEN-LAST:event_VehListActionPerformed

    private void VehListItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_VehListItemStateChanged
      
    }//GEN-LAST:event_VehListItemStateChanged

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        // TODO add your handling code here:
         // TODO add your handling code here:
        VehList.removeAllItems();
        String veh = jTextField1.getText().toLowerCase().toString();
        System.out.println(veh);
        for (int i = 0; i < carro.size(); i++) {
            if(carro.get(i).toLowerCase().contains(veh)){
                cmitem ss = new cmitem(carro.get(i), precc.get(i));
                VehList.addItem(ss);
            }
              
            
        }
        
        
        
        if(VehList.getItemCount() == 1){
            Object item = VehList.getSelectedItem();
            
                String value = ((cmitem)item).getValue();
                VehPriceInput1.setText(value);
            
            
        }
    }//GEN-LAST:event_jTextField1KeyReleased

    private void TunePriceInput1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TunePriceInput1KeyReleased
        int vehprice = Integer.parseInt(VehPriceInput1.getText().toString());
        if(TunePriceInput1.getText() != null){
            int tuneprice = Integer.parseInt(TunePriceInput1.getText().toString());
            int tottax = vehprice + tuneprice;
            TaxPriceInput.setText(String.valueOf(tottax) + "$");
            BuyPriceInput.setText(String.valueOf(tottax * 0.50) + "$");
            SalePriceInput.setText(String.valueOf(tottax * 0.70) + "$");
        }
        
        
    }//GEN-LAST:event_TunePriceInput1KeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PriceCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PriceCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PriceCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PriceCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BuyPriceInput;
    private javax.swing.JLabel BuyPriceLabel;
    private javax.swing.JLabel PriceCalculatorTitle;
    private javax.swing.JTextField SalePriceInput;
    private javax.swing.JLabel SalePriceLabel;
    private javax.swing.JTextField TaxPriceInput;
    private javax.swing.JLabel TaxPriceLabel;
    private javax.swing.JTextField TunePriceInput1;
    private javax.swing.JLabel TunePriceLabel2;
    private javax.swing.JComboBox<Object> VehList;
    private javax.swing.JTextField VehPriceInput1;
    private javax.swing.JLabel VehPriceLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
